updated c++ client instructions
ni/monodrive-documentation pull request #295
Opened 2021-07-28 19:04 UTC by katiemacaulay

**Overview**
Customer was following getting started client instructions from readthedocs and mentioned that they wish they had read the Readme instead because it has better pictures and information. 

**Changes**
Updated the RTD getting started instructions from client repo instructions

https://monodrive.readthedocs.io/en/update_client_getting_started/cpp_client/cpp_quick_start/

2021-08-24 19:57 UTC, bradleynull requested changes
@katiemacaulay A few quick things with headings. Also need to discuss the installation stuff.

2021-08-24 19:57 UTC, bradleynull commented on docs/cpp_client/cpp_quick_start.md
> +#### Figure: Environment Variables
For some reason using 4 `#` renders as a top level header on my browser. Suggest re-styling this: 
![image](https://user-images.githubusercontent.com/6026642/130680720-63d43316-95a5-418b-83f0-1c9c314980ff.png)

2021-08-24 19:57 UTC, bradleynull commented on docs/cpp_client/cpp_quick_start.md
> +## Ubuntu 20.04 Prerequisites
The 18.04 is a lower level heading than the 20.04. Suggest making a single `## Ubuntu` section and sub-headings for 18.04 and 20.04

2021-08-24 19:57 UTC, bradleynull commented on docs/cpp_client/cpp_quick_start.md
> +## Installation to system on Ubuntu
As far as I know, there is no `install` target for the client. I think this should be removed.

2021-08-24 19:57 UTC, bradleynull commented on docs/cpp_client/cpp_quick_start.md
> +## Installation with Bazel
This should be a sub-heading of the Ubuntu section. Its simply showing how to use a separate compiler other than `gcc ` or `g++`

2021-08-24 19:57 UTC, bradleynull commented on docs/cpp_client/cpp_quick_start.md
> +## Installation to system on Ubuntu
Are these the instructions for installation with Bazel?

2021-09-03 21:21 UTC, katiemacaulay commented on docs/cpp_client/cpp_quick_start.md
> +contact support@monodrive.io to get access to the monoDrive Client repository,
checked and it is still being forwarded to this email

2021-09-03 23:00 UTC, bradleynull approved these changes
@katiemacaulay Looks good to go! Approved!

2021-09-03 23:12 UTC, merged